
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [23.5.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NEXT_WEBSITE_URL: ${{secrets.NEXT_WEBSITE_URL}}
      DATABASE_URI: ${{secrets.DATABASE_URI}}
      NEXT_PUBLIC_SERVER_URL: ${{secrets.NEXT_PUBLIC_SERVER_URL}}
      PAYLOAD_SECRET: ${{secrets.PAYLOAD_SECRET}}

    steps:
    - name: Checkout Github Repository
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        version: 10
        run_install: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Ensure we are in the proper Directory for the AutocraticDespair.com website.
      run: cd /home/jones/actions-runner/_work/autocraticdespair.com/autocraticdespair.com

    - name: Install dependencies
      run: pnpm install

    - name: write an .env file with commands
      run: echo "NEXT_PUBLIC_SERVER_URL=${{secrets.NEXT_PUBLIC_SERVER_URL}}" > .env.locally

    - name: add payload secret to env
      run: echo "PAYLOAD_SECRET=${{secrets.PAYLOAD_SECRET}}" >> .env.locally

    - name: add database uri to env
      run: echo "DATABASE_URI=${{secrets.DATABASE_URI}}" >> .env.locally

    - name: add next website
      run: echo "NEXT_WEBSITE_URL=${{secrets.NEXT_WEBSITE_URL}}" >> .env.locally

    - name: add google tag to env
      run: echo "NEXT_PUBLIC_GTAG=G-PX8ZPEGWLK" >> .env.locally

    - name: build the static website
      run: pnpm build

    - run: pm2 restart 0
